version: '3.9'

services:

  gateway:
    image: nginx:alpine
    ports:
      - "90:90"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fingerprint
      - aggregator
      - recommender
      - frontend

  fingerprint:
    build: ./services/fingerprint
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_URL=postgres://user:pass@db:5432/musicdb
    depends_on:
      - db

  aggregator:
    build: ./services/aggregator
    ports:
      - "8002:8000"

  recommender:
    build: ./services/recommender
    ports:
      - "8003:8000"
    depends_on:
      - vector_db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: musicdb
    volumes:
      - pg_data:/var/lib/postgresql/data

  vector_db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9002:9002"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    command: server /data --console-address ":9002"
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  qdrant_data:
  minio_data: